In [565]:
import pandas as pd 
import numpy as np

Predict the prices of the properties based on the features available to us

In [566]:
#data available with us
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

Now our input x variables are area_sqft and bedrooms and our target variable y is price

In [567]:
#shuffle data 
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

#train test split 
split_index = int(0.75 * len(df))

#75 % train 25 % test data split
train_df = df.iloc[:split_index]
test_df = df.iloc[split_index:]

X_train = train_df[["area_sqft","bedrooms"]]
y_train = train_df["price"]

X_test = test_df[["area_sqft","bedrooms"]]
y_test = test_df["price"]

In [568]:
#Fitting a linear regression model 
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [569]:
#Intercept part
print("Intercept:",model.intercept_)
print("Coefficient:",model.coef_)

Intercept: -8.74573378839591
Coefficient: [ 0.11023891 -1.15187713]

In [570]:
y_pred = model.predict(X_test)

result = pd.DataFrame({
"Actual":y_test.values,
"Predicted":y_pred
})

result

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [571]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print("MAE :",mae)

MAE : 7.133105802047773

In [572]:
#Revision 1 
import pandas as pd
import numpy as np

In [573]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [574]:
#Train test split 75 25 split

#random shuffling
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.75 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [575]:
#Fitting the model using linear regression
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [576]:
results = pd.DataFrame({
    "Actual":y_test,
    "Predicted":y_pred
})

results

   Actual   Predicted
6      90   99.189420
7     180  185.076792

In [577]:
#Coffiecient and intercept
#y = mx + c
print("Coefficient",model.coef_)
print("Intercept :",model.intercept_)

Coefficient [ 0.11023891 -1.15187713]
Intercept : -8.74573378839591

In [578]:
#Checking the error metrics
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print(f"Mean absolute error : {mae}")

Mean absolute error : 7.133105802047773

In [579]:
#Fitting separate models on area sqft and bedrooms
X_train_area = df_train[["area_sqft"]]
y_train_area = df_train["price"]

X_test_area = df_test[["area_sqft"]]
y_test_area = df_test["price"]

area_model = model.fit(X_train_area,y_train_area)

area_model_pred = model.predict(X_test_area)

mae_area = mean_absolute_error(y_test_area,area_model_pred)


results_area = pd.DataFrame({
    "Model Name": "Price predict w Area",
    "Actual":y_test.values,
    "Predicted":area_model_pred,
    "MAE":mae_area
})

print(results_area)




print(f"MAE on area : {mae_area}")

             Model Name  Actual   Predicted       MAE
0  Price predict w Area      90   99.081847  7.229801
1  Price predict w Area     180  185.377754  7.229801
MAE on area : 7.229800629590763

In [580]:
#Fitting the model on bedrooms only
X_train_b = df_train[["bedrooms"]]
y_train_b = df_train["price"]

X_test_b = df_test[["bedrooms"]]
y_test_b = df_test["price"]

model_b = model.fit(X_train_b,y_train_b)

y_pred_b = model_b.predict(X_test_b)

mae_b = mean_absolute_error(y_test_b,y_pred_b)
#result
results_b = pd.DataFrame({
    "Model Name": "Price predict w Bedrooms",
    "Actual":y_test_b.values,
    "Predicted":y_pred_b,
    "MAE":mae_b
})

results_b

                 Model Name  Actual   Predicted       MAE
0  Price predict w Bedrooms      90   95.681818  8.636364
1  Price predict w Bedrooms     180  191.590909  8.636364

In [581]:
best_model = ""
# results_area
# Comparing both the models 
mae_a = results_area["MAE"].iloc[0]
mae_b = results_b["MAE"].iloc[0]
model_a = "Area Model"
model_b = "Bedroom Model"

    # mae = float(results["MAE"])

if mae_a > mae_b:

    best_model = model_b

elif mae_a < mae_b:
    best_model = model_a

#same performance condition 
if mae_a == mae_b:
    best_model += model_a
    best_model += ","
    best_model += model_b

print(f"Best model as per mae comparison : {best_model}")

Best model as per mae comparison : Area Model

In [582]:
#Revision 2
import pandas as pd
import numpy as np

In [583]:
#Available data to us
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)
df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [584]:
#Shuffling 

df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.75 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [585]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [586]:
y_pred = model.predict(X_test)

results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [587]:
print(model.coef_)
print(model.intercept_)

[ 0.11023891 -1.15187713]
-8.74573378839591

In [588]:
#checking the error
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print("MAE :",mae)

MAE : 7.133105802047773

In [589]:
# #Xgboost model 
# from xgboost import XGBRegressor

# model = XGBRegressor(
#     learning_rate = 0.1,
#     max_depth = 5,
#     n_estimators = 50,
#     random_state = 42
# )

# model.fit(X_train,y_train)

In [590]:
y_pred = model.predict(X_test)

mae_xgb = mean_absolute_error(y_test,y_pred)

print("MAE of XGB Model",mae_xgb)

MAE of XGB Model 7.133105802047773

In [591]:
#Revision 3 
import pandas as pd 
import numpy as np

In [592]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [593]:
#shuffling splitting

df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [594]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model = model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [595]:
print(model.intercept_)
print(model.coef_)

-8.74573378839591
[ 0.11023891 -1.15187713]

In [596]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

In [597]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print(mae)

7.133105802047773

In [598]:
#Revision 4 
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [599]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [600]:
#shuffling

df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [601]:
model = model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [602]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [603]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

In [604]:
print(f"MAE of the model :{mean_absolute_error(y_test,y_pred)}")

MAE of the model :7.133105802047773

In [605]:
#Revision 5 
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [606]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [607]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [608]:
model = LinearRegression()

model = model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [609]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [610]:
#results

results = pd.DataFrame(
    {"Actual":y_test.values,
     "Predicted":y_pred}
)

In [611]:
mae = mean_absolute_error(y_test,y_pred)

print("MAE of the model",mae)

MAE of the model 7.133105802047773

In [612]:
#Revision 6 
import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [613]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [614]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.75 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [615]:
model = LinearRegression()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [616]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [617]:
#results 
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [618]:
mae = mean_absolute_error(y_test,y_pred)

print(f"MAE : {mae}")

MAE : 7.133105802047773

In [619]:
import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [620]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}


df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [621]:
#shuffling and sampling

df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [622]:
model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [623]:
y_pred = model.predict(X_test)

In [624]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [625]:
results = pd.DataFrame(
    {"Actual":y_test.values,
     "Predicted":y_pred}
)

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [626]:
mae = mean_absolute_error(y_test,y_pred)

print(f"MAE for the model trained is : {mae}")

MAE for the model trained is : 7.133105802047773

In [627]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [628]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [629]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.75 * len(df))

df_train = df.iloc[:split_index] # stop at 75 % data for training 
df_test = df.iloc[split_index:] # take the other 25% for testing

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [630]:
#Initializing the model 

model = LinearRegression()

In [631]:
#Fitting the model 
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [632]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [633]:
#results 
results = pd.DataFrame(
    {"Actual":y_test.values,
     "Predicted":y_pred}
)

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [634]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error : {mae}")

Mean absolute error : 7.133105802047773

In [635]:
import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [636]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [637]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test['price']

In [638]:
#Initializing the model

model = LinearRegression()

In [639]:
#Fitting the model
model.fit(X_train,y_train)

LinearRegression()

In [640]:
#Predicting using the model 

y_pred = model.predict(X_test)

In [641]:
#Checking the coefficient and intercept

model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [642]:
#Checking the results

results = pd.DataFrame(
    {"Actual":y_test.values,
     "Predicted":y_pred}
)

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [643]:
#Checking the evalation metrics

mae = mean_absolute_error(y_test,y_pred)

print(f"Mean abosulute error for the model : {mae}")

Mean abosulute error for the model : 7.133105802047773

In [644]:
#Revision 9
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [645]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [646]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test['price']

In [647]:
#Model initialization

model = LinearRegression()

In [648]:
model.fit(X_train,y_train)

LinearRegression()

In [649]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [650]:
y_pred = model.predict(X_test)

In [651]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [652]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error : {mae}")

Mean absolute error : 7.133105802047773

In [653]:
#Revision 10
import pandas as pd
import numpy as np 
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression

In [654]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [655]:
df.columns.to_list()

df.isna().sum()

area_sqft    0
bedrooms     0
price        0
dtype: int64

In [656]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train['price']

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test['price']

In [657]:
model = LinearRegression()

In [658]:
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [659]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [660]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [661]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error : {mae}")

Mean absolute error : 7.133105802047773

In [662]:
#Revision 11 
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [663]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [664]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train['price']

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test['price']

In [665]:
model = LinearRegression()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [666]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [667]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [668]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error : {mae}")

Mean absolute error : 7.133105802047773

In [669]:
#Revision 12 
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [670]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [671]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train['price']

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test['price']

In [672]:
model = LinearRegression()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [673]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [674]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
}
    )

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [675]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error for the model : {mae}")

Mean absolute error for the model : 7.133105802047773

In [676]:
#Revision 13
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [677]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [678]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train['price']

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test['price']

In [679]:
model = LinearRegression()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [680]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [681]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [682]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error : {mae}")

Mean absolute error : 7.133105802047773

In [683]:
#Revision 14
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [684]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [685]:
df.describe()

         area_sqft  bedrooms       price
count     8.000000  8.000000    8.000000
mean   1187.500000  2.500000  117.500000
std     538.350656  1.195229   57.817447
min     500.000000  1.000000   50.000000
25%     775.000000  1.750000   72.500000
50%    1100.000000  2.500000  105.000000
75%    1575.000000  3.250000  157.500000
max    2000.000000  4.000000  210.000000

In [686]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

In [687]:
#Revision 15
import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [688]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [689]:
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   area_sqft  8 non-null      int64
 1   bedrooms   8 non-null      int64
 2   price      8 non-null      int64
dtypes: int64(3)
memory usage: 320.0 bytes

In [690]:
#Data splitting logic
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]

df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [691]:
#Initializing the model

model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [692]:
y_pred = model.predict(X_test)

y_pred

array([ 99.1894198 , 185.07679181])

In [693]:
model.intercept_
model.coef_

array([ 0.11023891, -1.15187713])

In [694]:
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

   Actual   Predicted
0      90   99.189420
1     180  185.076792

In [695]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean abosulute error of the model is : {mae}")

Mean abosulute error of the model is : 7.133105802047773

In [696]:
#Revision 16
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_absolute_percentage_error

In [697]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data)

df.head()

   area_sqft  bedrooms  price
0        500         1     50
1        700         1     65
2        800         2     75
3       1000         2     90
4       1200         3    120

In [700]:
#Train, Test split logic

df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train = df.iloc[:split_index]
df_test = df.iloc[split_index:]

X_train = df_train[["area_sqft","bedrooms"]]
y_train = df_train["price"]

X_test = df_test[["area_sqft","bedrooms"]]
y_test = df_test["price"]

In [701]:
model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [702]:
y_pred = model.predict(X_test)

In [703]:
model.coef_
model.intercept_

np.float64(-4.318181818181813)

In [704]:
#Results
results = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

results

   Actual   Predicted
0     210  200.227273
1      90   97.954545

In [705]:
mae = mean_absolute_error(y_test,y_pred)

print(f"Mean absolute error : {mae}")

Mean absolute error : 8.86363636363636

In [ ]:
import pandas as pd 
import numpy as np 
from sklearn.metrics import roc_auc_score,classification_report,mean_absolute_error
from sklearn.linear_model import LinearRegression

In [ ]:
data = {
    "area_sqft": [500, 700, 800, 1000, 1200, 1500, 1800, 2000],
    "bedrooms":  [1,   1,   2,    2,    3,    3,    4,    4],
    "price":    [50,  65,  75,   90,   120,  150,  180,  210]  # in lakhs
}

df = pd.DataFrame(data) 

df.head()

In [ ]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

split_index = int(0.8 * len(df))

df_train